### ISSUE TITLE
Dependencies and privacy questions

### ISSUE THREAD

**Issue by Tony-il-Capo** [sreichholf/dreamDroid#93]
Hi
I'm running dreamDroid on a google free device, I use the apk(s) from here (/app), I always get a toast notification when starting the app, something like 'Billing service is not available'

**Why is that? Why this needs billing service?**

Also, sometimes I see firewall logs of connection attempts made by dreamDroid to outside the LAN zone (that end being blocked). I have  usage statistics disabled.

**Why these connections??**

**That said, where's the privacy policy for this app?**

**Btw, why the target platforms are only "DreamBox"?** This will actually work on any Enigma2 stb with the OpenWebIf installed.

Thanks for your time.

**Comment by sreichholf** [comment]
Billing service is only used for donations. As you may have realized it works fine without. You can use the amazon-version which is "play service free" and doesn't pop up that message all the time (I'm not sure I've built the amazon flavor of the latest version but i can do that the next time I'm building an official release).

https://dreamdroid.org/privacy.html

Because there are known issues issues with OpenWebIf. And even though this is my private project, I am still employed by Dream, which makes me not wanna include explicit support for others.

**Comment by Tony-il-Capo** [comment]
Okay, many thanks for the explanation.

**Comment by sreichholf** [comment]
You're welcome
